name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
          dotnet-version: | 
            6.0.x
            7.0.x
            8.0.x
    - name: Install dependencies
      run: dotnet restore src/DotNetSearch.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore  src/DotNetSearch.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal  src/DotNetSearch.sln
